version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: "loopang"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "test_db"
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    ports:
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "8687lee@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
# loopang:
#   build:
#     context: .
#     dockerfile: ./Dockerfile
#   command:
#     - python App.py
#   ports:
#     - "8080:8080"
#   volumes:
#     - ./:/app

volumes:
  postgres-data:
  
