version: '3.5'
services:
  db:
    container_name: postgres
    image: postgres:latest
    #restart: always
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: "loopang"
      POSTGRES_PASSWORD: "1234"
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432
    networks:
      services-network:
        aliases:
          - db
      
  loopang:
    container_name: loopang
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    depends_on:
      - db
    links:
      - db
    networks:
      services-network:
        aliases:
          - web
networks:
  services-network:
    name: service-network
    driver: bridge

volumes:
  db-data:
    driver: local
#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    restart: always
#    depends_on:
#      - postgres
#    ports:
#      - 80:80
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "8687lee@gmail.com"
#      PGADMIN_DEFAULT_PASSWORD: "admin"

