version: '3.5'
services:
  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    env_file:
      - ./DockerENV.env
    volumes:
      - ./docker/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
      
  loopang:
    container_name: loopang
    image: loopang:latest
    restart: always
    env_file:
      - ./DockerENV.env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - ./music:/app/music/
    depends_on:
      - db
    links:
      - db

#volumes:
#  db-data:
#    driver: local

#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    restart: always
#    depends_on:
#      - postgres
#    ports:
#      - 80:80
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "8687lee@gmail.com"
#      PGADMIN_DEFAULT_PASSWORD: "admin"

