version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: "loopang"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "test_db"
    ports:
      - 5432:5432
    volumes:
      - var/lib/postgresql/data
#  loopang:
#    container_name: loopang
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#    restart: always
#    ports:
#      - "5000:8080"
#    depends_on:
#      - postgres
#    volumes:
#      - ./:/app
#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    restart: always
#    depends_on:
#      - postgres
#    ports:
#      - 80:80
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "8687lee@gmail.com"
#      PGADMIN_DEFAULT_PASSWORD: "admin"

